version: '3.8'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    environment:
      - PORT=1488
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    ports:
      - "1488:1488"
